### PR TITLE
Fix bug that was adding too many jvectormap-tip divs

### PR DESCRIPTION
**Pull request by mmazanec22**

### CODE REVIEW

**Comment by vforgione** [comment]
Where did these source files come from? There's just so much here for me to run through. Is this just a local copy of an NPM installed module with a few edits?

**Comment by mmazanec22** [comment]
Sooo... I forked this from another repo without looking super hard at it.  Turns out they're using jVectorMap, which states that "Starting version 2.0.0 jVectorMap is dual-licenses [sic] under the terms of GPL and commercial license."  Is this going to be a problem?

**Comment by ajrgrubbs** [comment]
Better ask a lawyer? I wonder if we have one...

**Comment by vforgione** [comment]
I would **not** use this in that case. But, yeah, ask a lawyer.

**Comment by dm00000** [comment]
Developer license costs $150. It's fine where it is right now

**Comment by dm00000** [comment]
Why is the PR a minified file and the commit of an entire new file?

**Comment by dm00000** [comment]
After speaking with Melanie about this clusterfuck of a PR, we've come to a conclusion that she needed to start with a clean state of both files then made her changes so we can look at the differences. She promises not to do this again.

**Comment by mmazanec22** [comment]
@dm00000 it's slightly less of a clusterfuck now

**Pull request merged**
